services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pg-agent-memory-db
    environment:
      POSTGRES_DB: agent_memory
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: agent_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_user -d agent_memory"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: